### PR TITLE
Ci cd

### PR DESCRIPTION
**Pull request by pedrohba1**
How strict should be clippy? We can set it to error on warning to break CI

### CODE REVIEW

**Review by srosati — CHANGES_REQUESTED** [review]
Code seems mostly fine, i would suggest adding check for cargo fmt as well, theres an option for it to throw an error if the formatting is wrong.

Also, make sure the ci-cd passes before we merge this PR, i would suggest that testing on just stable rust would be fine, maybe it would be better to test just stable rust in different platforms (ubuntu, macos, windows) if possible

**Comment by pedrohba1** [comment]
After running clippy and attempting to fix some of the warnings, one of the complaints caught my attention in particular:

It is "solved" by simply
```
    if header_roots != block_header_roots {
        return Err(BlockHeaderError::MismatchedRoots(Box::new((
            header_roots,
            block_header_roots,
        ))));
    }
    
    /// headers/errors.rs
      #[error("Mismatched roots")]
    MismatchedRoots(Box<(BlockHeaderRoots, BlockHeaderRoots)>),
  
   ```
However, [given this discussion](https://users.rust-lang.org/t/non-exhaustive-in-library-will-make-things-difficult-best-practice/80877), I'm not sure if it is the correct approach. It does stop the warning though. 

I think we should take a bit more care on this one, because in the discussion it mentions:
>I think a first question to ask that you seem to have skipped over is, do you care? [Checking the playground 2](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b13e241d686724b0831b90e48451c65a), MachineError is exactly 128 bytes which is a trivial amount unless you're targeting embedded systems or extremely hot loops.

And I believe in this scenario we could consider our code to be a "hot loop"

**Comment by srosati** [comment]
Your solution is actually suggested by clippy, in the warning you can see:
> for example by boxing large elements

Regarding the discussion, i assume you mean an issue with breaking changes to previos version? In that case it shouldn't be an issue, since 0.1 is not officially released.

**Comment by pedrohba1** [comment]
> Your solution is actually suggested by clippy, in the warning you can see:
> 
> > for example by boxing large elements
> 
> Regarding the discussion, i assume you mean an issue with breaking changes to previos version? In that case it shouldn't be an issue, since 0.1 is not officially released.

No Breaking changes. It just werks. As you explained, error types are nested so it solves the problem by just fixing the `MismatchedRoots`.

**Review by srosati — APPROVED** [review]

**Pull request merged**
